[package]
name = "honny-craft-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = { version = "0.4" }
lazy_static = "1.4.0"
crossterm = "0.26.1"

# Network
renet = "0.0.11"

# ECS
hecs = "0.10.3"

# Async channels
crossbeam = "0.8.2"
crossbeam-channel = "0.5"

# ARGS
clap = { version = "4.2.1", features = ["string", "derive"] }

# Noise
bracket-lib = "~0.8"
bracket-noise = "~0.8"
bracket-random = "~0.8"

# Schematics
flate2 = "1.0"
fastnbt = "2"
